fioprotocol/fio-dashboard

client/src/components/PasswordRecoveryForm/PasswordRecoveryForm.jsx
client/src/redux/notifications/reducer.js
server/src/services/users/SetRecovery.mjs

* Hide recovery notification after secret set
* Change min valid answer length
Co-authored-by: trukhilio <trukhantech@gmail.com>

Hide recovery notification after secret set (#20)

---

client/src/components/AddressDomainForm/AddressForm.jsx
client/src/components/AddressDomainForm/DomainForm.jsx
client/src/components/Input/Input.jsx
client/src/components/LoginForm/LoginForm.jsx
client/src/components/LoginForm/index.js
client/src/redux/edge/reducer.js
client/src/redux/edge/selectors.js
client/src/redux/notify/sagas.js

* BD-2405 sign in validation + input fixes

BD-2405 sign in validation + input fixes (#31)

---

client/src/components/AddressDomainBadge/AddressDomainBadge.jsx
client/src/components/AddressDomainForm/FormContainer.jsx
client/src/components/Cart/Cart.jsx
client/src/components/DomainsBanner/DomainsBanner.jsx
client/src/components/MainHeader/MainHeader.jsx
client/src/components/Notifications/Notifications.jsx
client/src/components/Notifications/index.js
client/src/components/PasswordRecoveryForm/PasswordRecoveryForm.jsx
client/src/components/ScrollToTop.jsx
client/src/constants/labels.js
client/src/constants/routes.js
client/src/pages/CartPage/CartPage.jsx
client/src/pages/CheckoutPage/CheckoutPage.jsx
client/src/pages/PurchasePage/PurchasePage.jsx
client/src/redux/profile/sagas.js
client/src/routes.jsx
client/src/services/CartTimeout.jsx
server/src/models/Notification.mjs
server/src/services/notifications/Create.mjs

Show notifications on specified pages, you could specify pages for each notification. Changed fio address/domain selection urls. Fixed redirecting on cart autoclrear - redirect only on checkout flow.
* Add pagesToShow to notification object. 
* Remove state from notifications component. 
* Show notification due to pathname. 
* Redirect on cart autoclear only from list of pages.
* Change fio address/domain selection pages routes

Notifications appearance changes.

---

client/src/components/AddressDomainForm/AddressForm.jsx
client/src/components/CheckoutPurchaseContainer/CheckoutPurchaseComponents.jsx
client/src/components/ScrollToTop.jsx
client/src/pages/CartPage/CartPage.jsx
client/src/pages/CheckoutPage/CheckoutPage.jsx
client/src/pages/CheckoutPage/index.js
client/src/pages/HomePage/HomePage.jsx
client/src/pages/HomePage/index.js

- fixed homepage address selection redux state
- made dashboard page as home for logged in users
- fixed price recalculation on cart page
- fixed price changes aftereffects on purchase

BD-2422. Registration flow fixes.

---

client/src/components/AddressDomainForm/AddressForm.jsx
client/src/components/AddressDomainForm/DomainForm.jsx
client/src/components/Input/Input.jsx

* transform address and domain names to lowercase on change
* set default values for suffix and lowerCased on input

BD-2616. Convert address and domain to lowercase on change.

---

client/src/components/AddressDomainForm/AddressDomainForm.jsx
client/src/components/AddressDomainForm/AddressDomainForm.module.scss
client/src/components/AddressDomainForm/FormContainer.jsx
client/src/components/LayoutContainer/LayoutContainer.module.scss

- change width of action button,
- set max width for layout container

BD-2611. Address selection form UI 

---

client/src/components/AuthContainer/AuthContainer.jsx
client/src/components/CheckoutPurchaseContainer/CheckoutPurchaseContainer.jsx
client/src/components/PasswordRecoveryForm/PasswordRecoveryForm.jsx
client/src/pages/DashboardPage/DashboardPage.jsx
client/src/pages/HomePage/HomePage.jsx
client/src/pages/PurchasePage/PurchasePage.jsx
client/src/redux/profile/sagas.js
client/src/routes.jsx
client/src/services/CartTimeout.jsx

- Set dashboard page as home for authed users

Home page refactor

---

client/src/components/CreateAccountForm/CreateAccountForm.jsx

- add props to super in constructor of create account component

Fix props to super

---

client/src/components/AddressDomainCart/AddressDomainCart.jsx
client/src/components/AddressDomainCart/index.js
client/src/redux/modal/reducer.js
client/src/redux/modal/selectors.js
client/src/redux/profile/sagas.js
client/src/redux/router/actions.js
client/src/redux/router/reducer.js
client/src/redux/router/selectors.js

- move redirect from modal to route reducer, 
- go to create account page on checkout now button click

checkout-now-redirect

---

client/src/components/AddressDomainForm/AddressDomainForm.module.scss
client/src/components/AddressDomainForm/FormContainer.jsx

- make loader icon to the right side of the address form submit button text

address form submit button loader

---

client/src/components/Input/Input.jsx
client/src/components/Input/Input.module.scss

- fix right padding on password input with two icons

Input padding fix

---

client/src/components/ManagePageContainer/ManagePageContainer.tsx
client/src/components/ManagePageContainer/types.d.ts
client/src/pages/FioAddressManagePage/index.tsx
client/src/pages/FioDomainManagePage/index.tsx
client/src/redux/profile/reducer.ts
client/src/redux/profile/selectors.js

* fix auth redirect on address/domain page

Fix auth redirect on address/domain page

---

client/src/components/ManagePageContainer/ManagePageComponents.module.scss
client/src/components/ManagePageContainer/ManagePageComponents.tsx
client/src/components/ManagePageContainer/ManagePageContainer.module.scss
client/src/components/ManagePageContainer/ManagePageContainer.tsx

- fix list layout
- update text
- fix scrollbar

Fix BD-2540 address/domain list

---

client/src/components/PurchaseNow/PurchaseNow.jsx
client/src/components/PurchaseNow/index.js
client/src/components/PurchaseNow/middleware.js
client/src/redux/edge/actions.js
client/src/redux/edge/reducer.js
client/src/utils.ts

…testnet env. Check for processing on purchase.

Purchase with wrong api base url fix

---

client/src/components/FioNameTransfer/FioNameTransferContainer/FioNameTransferContainer.tsx
client/src/components/Input/Input.module.scss
client/src/components/Input/InputActionButtons.module.scss
client/src/components/Input/InputActionButtons.tsx
client/src/components/Input/InputRedux.tsx

- change inline styles from input redux to classes

Redux input styles changes

---

client/src/components/FioNameTransfer/FioNameTransferContainer/FioNameTransferContainer.tsx
client/src/components/FioNameTransfer/FioNameTransferSuccess/FioNameTransferSuccess.tsx
client/src/components/FioNameTransfer/FioNameTransferSuccess/types.d.ts
client/src/constants/routes.js
client/src/pages/FioAddressTransferSuccessPage/FioAddressTransferSuccessPage.tsx
client/src/pages/FioDomainTransferSuccessPage/FioDomainTransferSuccessPage.tsx
client/src/routes.jsx

- Add errored state to transfer results page
- Rename names of routes to transfer results
- Rename transfer component prop types

BD-2547. Transfer results

---

client/src/components/Badges/DomainStatusBadge/DomainStatusBadge.module.scss
client/src/components/Badges/DomainStatusBadge/DomainStatusBadge.tsx
client/src/components/FioDomainStatusChange/FioDomainStatusChangeContainer/FioDomainStatusChangeContainer.module.scss
client/src/components/FioDomainStatusChange/FioDomainStatusChangeContainer/FioDomainStatusChangeContainer.tsx
client/src/components/FioDomainStatusChange/FioDomainStatusChangeContainer/index.ts
client/src/components/FioDomainStatusChange/FioDomainStatusChangeContainer/types.d.ts
client/src/components/FioDomainStatusChange/FioDomainStatusChangeResults/FioDomainStatusChangeResults.module.scss
client/src/components/FioDomainStatusChange/FioDomainStatusChangeResults/FioDomainStatusChangeResults.tsx
client/src/components/FioDomainStatusChange/FioDomainStatusChangeResults/index.ts
client/src/components/FioDomainStatusChange/FioDomainStatusChangeResults/types.d.ts
client/src/components/ManagePageContainer/ManagePageComponents.module.scss
client/src/components/ManagePageContainer/ManagePageComponents.tsx
client/src/components/ManagePageContainer/constants.tsx
client/src/constants/common.js
client/src/constants/routes.js
client/src/pages/FioDomainStatusChangePage/FioDomainStatusChangePage.tsx
client/src/pages/FioDomainStatusChangePage/index.ts
client/src/pages/FioDomainStatusChangeResultsPage/FioDomainStatusChangeResultsPage.tsx
client/src/pages/FioDomainStatusChangeResultsPage/index.ts
client/src/routes.jsx
client/src/types.d.ts
client/src/utils.ts

- Create domain status change and results pages

BD-2553 Domain status change and results pages

---

client/src/components/FioDomainStatusChange/FioDomainStatusChangeContainer.tsx

- Add info badge to domain status change

BD-2552-domain-status

---

client/src/components/Modal/GenericErrorModal/GenericErrorModal.tsx
client/src/redux/modal/actions.js
client/src/redux/modal/reducer.js
client/src/redux/modal/sagas.ts
client/src/redux/notify/constants.ts
client/src/redux/notify/sagas.js
client/src/redux/sagas.js

- Show account recovery generic error on bad link
- Connect generic error

BD-2880 recovery account

---

client/src/pages/PrivacyPolicyPage/PrivacyPolicyPage.tsx

BD-2640 privacy and terms

---

client/src/components/Settings/components/PasswordRecovery/ResendEmail/ResendEmail.tsx

- Fix app crash on failed pin confirmation

BD-2663 settings password recovery fix

---

client/src/api/fio.ts
client/src/components/CreateAccountForm/CreateAccountForm.tsx
client/src/components/Modal/EmailConfirmBlocker/EmailConfirmBlocker.tsx
client/src/components/SignNft/SignNft.tsx
client/src/components/SignNft/SignNftForm.tsx
client/src/components/SignNft/types.d.ts
client/src/components/SignNft/validation.ts
client/src/pages/FioAddressNftPage/FioAddressNftPage.tsx
client/src/pages/FioAddressSignPage/FioAddressSignPage.tsx
client/src/pages/RefHomePage/RefHomePage.tsx
client/src/pages/RefSignNftPage/RefSignNftPage.tsx
client/src/redux/fio/actions.ts
client/src/redux/refProfile/actions.ts
client/src/redux/refProfile/reducer.ts
client/src/services/RefFlow.tsx
client/src/types.d.ts

- upgrade types for Nft item
- use camelCase in Nft item

BD-2876 NFT types format

---

client/src/components/Badges/LowBalanceBadge/LowBalanceBadge.tsx

Remove action button from Low balance badge

BD-3014 Make Deposit button

---

client/src/pages/NftValidationPage/components/NftItemResult/GenericNftItemResult.tsx

BD-2955 Image upload

---

.gitignore
client/src/components/Notifications/Notifications.jsx
client/src/components/PasswordRecoveryForm/PasswordRecoveryForm.jsx
client/src/constants/notifications.ts
client/src/pages/EmailConfirmationPage/EmailConfirmationPage.tsx
client/src/redux/profile/sagas.js
client/src/services/CartTimeout.jsx
client/src/types.d.ts
server/src/migrations/20211104134832-add-types-in-notifications.js
server/src/models/Notification.mjs
server/src/notifications.mjs
server/src/services/notifications/Create.mjs
server/src/services/users/Create.mjs

BD-2993 Refactor notifications

---

client/src/components/AddressDomainCart/AddressDomainCart.jsx
client/src/components/AddressDomainCart/index.js

Fix checkout redirect for multiple wallets and auth user

BD-2947 checkout redirect

---

client/src/components/Settings/components/ChangePin/ChangePin.tsx

- Fix text in change pin settings item

BD-2657 Change pin settings

---

client/src/components/common/TransactionProcessing/Processing.tsx
client/src/pages/UpdateEmailPage/UpdateEmailPage.tsx
client/src/pages/UpdateEmailPage/index.ts
client/src/redux/notify/sagas.js
client/src/redux/profile/actions.ts
client/src/redux/profile/reducer.ts

Set processing type loader for new email confirming

BD-2651. Settings update email

---

client/src/components/AddressDomainCart/AddressDomainCart.jsx
client/src/components/AddressDomainForm/AddressDomainForm.jsx
client/src/components/AddressDomainForm/FormContainer.jsx
client/src/components/AddressDomainForm/Notifications.tsx
client/src/components/Cart/CartAmount.jsx
client/src/components/CartSmallContainer/CartSmallContainer.jsx
client/src/components/CartSmallContainer/CartSmallContainer.module.scss
client/src/components/InfoBadge/InfoBadge.module.scss
client/src/components/InfoBadge/InfoBadge.tsx
package.json

- Move price to notification for mobile
- Scroll to notification 'Available' on mobile submit form

BD-2721. Mobile UI

---

client/src/assets/styles/global.scss
client/src/components/Link/Link.tsx
client/src/components/LinkTokenList/ActionContainer.tsx
client/src/components/LinkTokenList/styles/CommonLayout.module.scss
client/src/components/common/TransactionResults/components/LinkTokenListResults/LinkTokenListResults.tsx
client/src/components/common/TransactionResults/types.d.ts
client/src/pages/AddTokenPage/AddTokenPage.tsx
client/src/pages/AddTokenPage/copmonents/AddTokenForm.tsx
client/src/pages/AddTokenPage/index.ts
client/src/pages/AddTokenPage/types.d.ts
client/src/pages/AddTokenPage/validation.ts
client/src/pages/DeleteTokenPage/DeleteTokenPage.tsx
client/src/pages/DeleteTokenPage/index.ts
client/src/pages/EditTokenPage/EditTokenPage.tsx
client/src/pages/EditTokenPage/components/PublicAddressEdit.tsx
client/src/pages/EditTokenPage/index.ts
client/src/pages/TokenListPage/components/ActionButtons.tsx
client/src/util/hooks.ts

- Update props in ActionContainer and results page
- Remove currentFioAddress in usePublicAddresses hook

BD-2550. Link token list updates

---

client/src/components/ManagePageContainer/constants.tsx
client/src/components/PasswordRecoveryForm/PasswordRecoveryForm.jsx
client/src/constants/notifications.ts
client/src/pages/SettingsPage/components/PasswordRecovery/PasswordRecovery.tsx
server/src/migrations/20211104134832-add-types-in-notifications.js

Fix misspelled loose to lose in text messages

BD-3027. Misspelled in text messages

---

client/src/components/Link/Link.tsx
client/src/components/LoginForm/LoginForm.module.scss
client/src/components/LoginForm/LoginForm.tsx
client/src/components/LoginForm/UsernamePassword.tsx
client/src/pages/SettingsPage/components/TwoFactorAuth/TwoFactorAuth.tsx
client/src/pages/SettingsPage/components/TwoFactorAuth/components/TwoFactorDisable.tsx
client/src/pages/SettingsPage/components/TwoFactorAuth/components/TwoFactorEnable.tsx
client/src/pages/SettingsPage/components/TwoFactorAuth/types.d.ts

- Fix loading state in enable/disable 2FA settings button

BD-3185. 2FA fixes

---

client/src/components/AddressDomainForm/AddressDomainForm.jsx
client/src/components/AddressDomainForm/FormContainer.jsx
client/src/components/common/SubmitButton/SubmitButton.module.scss
client/src/components/common/SubmitButton/SubmitButton.tsx

Fix autoscroll after crypto handle selection on homepage

BD-3187. Fix autoscroll on CryptoHandle form

---

client/src/components/Input/Input.tsx
client/src/components/Input/TextInput.tsx
client/src/util/general.ts

- Trim and remove meta characters in string on paste input button

BD-3174. Trim text input field on paste

---

client/src/components/Badges/FioRequestStatusBadge/FioRequestStatusBadge.module.scss
client/src/components/Badges/FioRequestStatusBadge/FioRequestStatusBadge.tsx
client/src/components/ConvertedAmount/ConvertedAmount.tsx
client/src/components/EdgeConfirmAction/EdgeConfirmAction.tsx
client/src/components/EdgeConfirmAction/types.d.ts
client/src/components/common/CancelButton/CancelButton.module.scss
client/src/components/common/CancelButton/CancelButton.tsx
client/src/constants/common.ts
client/src/constants/fio.ts
client/src/pages/WalletPage/components/DecryptContentEdge.tsx
client/src/pages/WalletPage/components/FioDataDetails.tsx
client/src/pages/WalletPage/components/FioDataTab.tsx
client/src/pages/WalletPage/components/FioRequestsTab.tsx
client/src/pages/WalletPage/components/FioTransactionItem.tsx
client/src/pages/WalletPage/components/FioTransactionItemContent.tsx
client/src/pages/WalletPage/components/TransactionActionButtons.tsx
client/src/pages/WalletPage/components/TransactionDetailedItem.tsx
client/src/pages/WalletPage/components/TransactionDetailedModal.tsx
client/src/pages/WalletPage/components/TransactionDetailedTabs.tsx
client/src/pages/WalletPage/components/TransactionItems.tsx
client/src/pages/WalletPage/constants.ts
client/src/pages/WalletPage/styles/FioDataDetails.module.scss
client/src/pages/WalletPage/styles/FioRequestsTab.module.scss
client/src/pages/WalletPage/styles/TransactionActionButtons.module.scss
client/src/pages/WalletPage/styles/TransactionDetailedItem.module.scss
client/src/pages/WalletPage/styles/TransactionDetailedModal.module.scss
client/src/pages/WalletPage/styles/TransactionItems.module.scss
client/src/pages/WalletPage/types.d.ts
client/src/util/fio.ts
client/src/util/hooks.ts

- Add processing props to EdgeConfirmAction
- Create convert fio to usdc hook
- Add colour to CancelButton
- Create common request status badge
- Create ConvertAmount component
- Create modal component for details data
- Set Pin confirmation for edge wallet
- Create tabs for detailed modal

BD-3192. OBT data details

---

client/src/components/Counter/Counter.module.scss
client/src/components/Counter/Counter.tsx
client/src/components/LoginForm/Pin.tsx
client/src/components/PinConfirmModal/PinConfirmModal.tsx
client/src/components/PinForm/PinForm.module.scss
client/src/components/PinForm/PinForm.tsx
client/src/components/common/SubmitButton/SubmitButton.module.scss
client/src/components/common/SubmitButton/SubmitButton.tsx
client/src/constants/regExps.ts
client/src/types.d.ts

- Create Counter component
- Update type in SubmitButton
- Handle and show blocked pin error

BD-3211. Set blocked pin error

---

client/src/components/Badges/TokenBadge/TokenBadge.module.scss
client/src/components/Badges/TokenBadge/TokenBadge.tsx
client/src/components/Badges/TokenBadge/TokenBadgeDesktop.tsx
client/src/components/Badges/TokenBadge/TokenBadgeMobile.tsx
client/src/components/Badges/TokenBadge/types.d.ts
client/src/components/LinkTokenList/ActionContainer.tsx
client/src/components/LinkTokenList/styles/ActionContainer.module.scss
client/src/components/SignNft/components/SignNftForm/SignNftForm.tsx
client/src/components/common/FioName/FioName.module.scss
client/src/components/common/TransactionResults/components/LinkTokenListResults/LinkTokenListResults.tsx
client/src/components/common/TransactionResults/styles/LinkTokenListResults.module.scss
client/src/pages/DeleteTokenPage/styles/DeleteTokenItem.module.scss
client/src/pages/EditTokenPage/components/PublicAddressEdit.tsx
client/src/pages/EditTokenPage/styles/PublicAddressEdit.module.scss

- Add BundledTransaction title in LinkTokenList pages
- Handle edited token UI
- Fix TokenBadge Desktop and Mobile styles
- Fix FioName styles
- Fix SignNft styles

BD-2549 FIx Link token list UI

---

client/src/api/fio.ts
client/src/components/Badges/FioRequestStatusBadge/FioRequestStatusBadge.tsx
client/src/components/InfiniteScroll/InfiniteScroll.module.scss
client/src/components/InfiniteScroll/InfiniteScroll.tsx
client/src/components/ManagePageContainer/ManagePageContainer.tsx
client/src/constants/fio.ts
client/src/pages/MainLayout/MainLayout.jsx
client/src/pages/WalletPage/WalletPage.tsx
client/src/pages/WalletPage/components/FioDataTab.tsx
client/src/pages/WalletPage/components/FioRequestsTab.tsx
client/src/pages/WalletPage/components/FioTransactionItem.tsx
client/src/pages/WalletPage/components/TransactionItems.tsx
client/src/pages/WalletPage/components/WalletTabs.tsx
client/src/pages/WalletPage/index.ts
client/src/pages/WalletPage/types.d.ts
client/src/redux/fioWalletsData/actions.ts
client/src/redux/fioWalletsData/reducer.ts
client/src/redux/fioWalletsData/selectors.ts
client/src/redux/reducer.js
client/src/redux/store.js
client/src/services/WalletsDataFlow.tsx
client/src/types.d.ts
client/src/util/hooks.ts
client/src/utils.ts
package.json

fiosdk version need to be updated in order to support encrypted content fetch

BD-3193 Fio wallets data flow

---

client/src/components/ManagePageContainer/ManagePageContainer.tsx
client/src/components/ManagePageContainer/types.d.ts
client/src/pages/FioAddressManagePage/index.tsx
client/src/pages/FioDomainManagePage/index.tsx

- Handle logic to load exact count of limit items per scroll and initial load
- Rename constants

BD-3224. Fix lazy load data on management Address/Domain pages

---

client/src/components/common/TransactionResults/components/RejectFioRequestResults.tsx
client/src/components/common/TransactionResults/constants.ts
client/src/pages/RejectFioRequestPage/RejectFioRequestPage.tsx
client/src/pages/RejectFioRequestPage/components/RejectRequestEdge.tsx

- Set reject FIO request action
- Handle errors

BD-2678. Reject FIO request action

---

client/src/pages/RejectFioRequestPage/RejectFioRequestPage.tsx

- Change rejected request title to 'Rejected'

Updates. Change successful rejected request title

---

client/src/pages/WalletPage/styles/FioRecordFieldsList.module.scss

- Fix long content overlap in FIO Request details field

Fix. Long content overlap in FIO Request details field

---

client/src/components/common/TransactionResults/components/TokenTransferResults.tsx
client/src/components/common/TransactionResults/types.d.ts
client/src/pages/FioTokensRequestPage/FioTokensRequestPage.tsx
client/src/pages/FioTokensRequestPage/index.ts
client/src/pages/FioTokensRequestPage/types.d.ts
client/src/pages/RejectFioRequestPage/RejectFioRequestPage.tsx
client/src/pages/RejectFioRequestPage/index.ts
client/src/pages/SendPage/SendPage.tsx
client/src/pages/SendPage/components/SendEdgeWallet.tsx
client/src/pages/SendPage/components/SendTokensForm/SendTokensForm.tsx
client/src/pages/SendPage/index.ts
client/src/pages/SendPage/types.d.ts
client/src/pages/WalletPage/components/FioRecordDetailedAcctionButtons.tsx
client/src/redux/fio/actions.ts
client/src/redux/fio/reducer.ts
client/src/redux/fio/selectors.ts
client/src/routes.jsx
client/src/services/WalletsDataFlow.tsx

- Add fioRequestId to recordObtData 
- Handle onBack route on SendToken Page
- Move initialValues from SendTokenForm to SendPage
- Handle memo and fioRequest errors on send token

BD-3285. Pay FIO Request

---

client/src/components/FioNameRenew/FioNameRenewContainer.module.scss
client/src/components/ManagePageContainer/ManagePageComponents/ActionButtons.module.scss
client/src/components/ManagePageContainer/ManagePageComponents/ActionButtons.tsx
client/src/components/ManagePageContainer/ManagePageComponents/DesktopView.tsx
client/src/components/ManagePageContainer/ManagePageComponents/ItemComponent.module.scss
client/src/components/ManagePageContainer/ManagePageComponents/ItemComponent.tsx
client/src/components/ManagePageContainer/ManagePageComponents/UIView.module.scss
client/src/components/ManagePageContainer/constants.tsx

- Move Add bundles action button from Actions to Bundles column in ManagePage
- Fix long addresses in FioNameRenewContainer

BD-3291. Relocate Add bundles action button

---

client/src/pages/WalletPage/components/FioRecordsList.tsx
client/src/pages/WalletPage/styles/FioRecordDetailedItem.module.scss
client/src/pages/WalletPage/styles/FioRecordDetailedModal.module.scss

- Fix payment details obt data type in fio request
- Fix layout in fio request details

Fix. Fio payment details OBT data type

---

client/src/components/AccountRecovery/AccountRecoveryForm.tsx
client/src/components/AccountRecovery/validation.ts
client/src/components/LoginForm/UsernamePassword.tsx
client/src/components/LoginForm/components/TwoFactorCodeModal.tsx
client/src/components/LoginForm/components/validation.ts
client/src/components/PasswordRecoveryForm/PasswordRecoveryForm.jsx
client/src/components/PasswordRecoveryForm/validation.ts
client/src/components/SignNft/components/SignNftForm/SignNftForm.tsx
client/src/components/SignNft/components/SignNftForm/validation.ts
client/src/pages/ImportWalletPage/components/ImportWalletForm/ImportWalletForm.tsx
client/src/pages/ImportWalletPage/components/ImportWalletForm/validation.ts
client/src/pages/SettingsPage/components/ChangeEmail/ChangeEmailForm.tsx
client/src/pages/SettingsPage/components/ChangeEmail/validation.ts
client/src/pages/WalletPage/components/EditWalletNameForm/EditWalletNameForm.tsx
client/src/pages/WalletPage/components/EditWalletNameForm/validation.ts
client/src/pages/WalletPage/components/PasswordForm/PasswordForm.tsx
client/src/pages/WalletPage/components/PasswordForm/validation.ts
client/src/pages/WalletsPage/components/CreateWalletForm/CreateWalletForm.tsx
client/src/pages/WalletsPage/components/CreateWalletForm/validation.ts
client/src/util/general.ts
client/src/util/validators/fio-wallet-name.validator.ts
client/src/util/validators/has-lowercase-letter.validator.ts
client/src/util/validators/has-number-char.validator.ts
client/src/util/validators/has-uppercase-letter.validator.ts
client/src/util/validators/index.ts
client/src/util/validators/is-chain-code.validator.ts
client/src/util/validators/is-hash.validator.ts
client/src/util/validators/is-native-blockchain-public-address.validator.ts
client/src/util/validators/meta.validator.ts
client/src/util/validators/password-recovery-answer.validator.ts

BD-3179. Refactor use validators in forms

---

client/src/components/ChainCodeField/ChainCodeField.tsx
client/src/components/Input/ChainCodeCustomDropdown.tsx
client/src/components/Input/EditableSelect/EditableCustomComponents.tsx
client/src/components/Input/EditableSelect/EditableSelect.tsx
client/src/components/Input/styles/EditableSelect.module.scss
client/src/components/SignNft/SignNft.tsx
client/src/components/SignNft/components/SignNftForm/SignNftForm.tsx
client/src/pages/AddTokenPage/copmonents/AddTokenInput.tsx
client/src/pages/FioTokensRequestPage/components/RequestTokensForm/RequestTokensForm.tsx
client/src/pages/FioTokensRequestPage/components/RequestTokensForm/TokenDataFields.tsx
client/src/pages/FioTokensRequestPage/styles/TokenDataFields.module.scss
client/src/pages/NftValidationPage/components/ContractAddressField.tsx
client/src/pages/NftValidationPage/styles/GenericNftValidationField.module.scss
package.json

- Refactor chain code field
- Use react-select library
- Fix styles
- BD-3429 Fix Sign NFT page error

BD-3041. Editable chain code field

---

server/src/config/constants.js
server/src/emails/approveFioRequest/approveFioRequest.hbs
server/src/emails/balanceChange/balanceChange.hbs
server/src/emails/emailTemplate.mjs
server/src/emails/expiringDomains/expiringDomains.hbs
server/src/emails/lowBundleCount/lowBundleCount.hbs
server/src/emails/newFioRequest/newFioRequest.hbs
server/src/emails/rejectFioRequest/rejectFioRequest.hbs
server/src/services/emailSender.mjs

- Notification email templates
- Handle templates in emailSender

BD-3496 Notification Emails

---

package.json

- Force bash usage in widget build script

BD-3326. Fix widget build

---

client/src/components/Input/TextInput.tsx
client/src/util/general.ts

- Fix input cursor position after text transform

BD-3587. Fix input cursor position

---

client/src/components/PinForm/PinForm.tsx

BD-3617. PIN entry freeze

---

client/src/components/AddressDomainCart/AddressDomainCart.tsx
client/src/pages/CartPage/CartPage.tsx
client/src/pages/CheckoutPage/CheckoutPage.tsx
client/src/utils.ts

- Fix recalculate free crypto handle cart item

BD-3616. Fix free crypto handle

---

client/src/components/Input/TextInput.tsx

- Fix address widget custom domain input issue

BD-3638. Fix address widget custom domain input issue

---

client/src/components/EdgeConfirmAction/EdgeConfirmAction.tsx
client/src/components/EdgeConfirmAction/index.ts
client/src/components/EdgeConfirmAction/types.d.ts
client/src/redux/fio/actions.ts
client/src/redux/refProfile/sagas.ts
client/src/util/general.ts

- Fix redirect after successed sign NFT of containied flow

Fix. Contained flow redirect hot fix

---

client/src/components/AddressDomainForm/AddressForm.tsx

- Fix customValue issue on domain dropdown

Fix. Domain dropdown issue

---

client/src/types.d.ts
client/src/util/homePage.ts

- Handle actionText on ref and contained flow

Fix. DASH-38 UI/UX Action text

---

client/src/components/Navigation/Navigation.tsx
client/src/components/common/TransactionResults/components/PaymentDetailsResults.tsx
client/src/pages/WalletPage/components/FioRecordFieldContent.tsx
client/src/pages/WalletPage/components/FioRecordFieldsList.tsx

- Fix FIO Request info amount code
- Fix active status token tab on homepage

Fix. DASH-85 FIO Request amount issue

---

client/src/components/AddressWidget/AddressWidget.module.scss

Fix. DASH-90 Homepage subtitle width

---

client/src/util/general.ts

- Show to user local time instead of UTC

Fix. DASH-83 Timestamp issue

---

client/src/components/Input/styles/EditableSelect.module.scss

- Fix editable select disabled state visibility

Fix. DASH-110 Editable select issue

---

client/src/api/ref-profile.ts
client/src/redux/refProfile/actions.ts
client/src/services/Ref.tsx
server/src/router.mjs
server/src/services/refProfile/Info.mjs

Update. Ref profile get info changes

---

client/src/components/common/TransactionResults/components/TransferResults/TransferResults.tsx
client/src/pages/WalletPage/WalletPage.tsx
client/src/pages/WalletPage/styles/WalletPage.module.scss
client/src/pages/WalletsPage/WalletsPage.tsx
client/src/pages/WalletsPage/components/Title.tsx
client/src/pages/WalletsPage/styles/ActionButtonsContainer.module.scss
client/src/pages/WalletsPage/styles/Title.module.scss
client/src/pages/WalletsPage/styles/WalletsPage.module.scss

- Fix transfer ownership long FIO Crypto Handle title
- Fix long wallet name title, refactor title on Token and Wallet pages

Fix. DASH-87 UI issues

---

client/src/components/Cart/Cart.tsx

- Change inscription in cart to more propriate

Update. DSAH-91 Change cart inscription

---

client/src/pages/DashboardPage/DashboardPage.tsx

- Update dashboard manage address button title to manage handle

Update. DASH-108 Update dashboard manage address button title

---

client/src/redux/containedFlow/sagas.ts

- Fix history import in contained flow sagas

Fix. Fix history import

---

client/src/pages/FioAddressSignPage/FioAddressSignPage.tsx
client/src/redux/containedFlow/sagas.ts

- Registration step. Redirect to checkout page if we have items in cart, if no - redirect to FIO address selection page
- Fix FioAddressSignPage if we have no state

Fix. DASH-107 Contained flow fixes

---

client/src/api/fio.ts

- Fix roe type in getBalance fio api method

Fix. DASH-86 BigInt error

---

client/src/components/AddressWidget/AddressWidget.module.scss

Fix. DASH-127 Ref logo mobile view

---

client/src/components/Navigation/Navigation.tsx
client/src/constants/labels.ts
client/src/constants/routes.ts
client/src/hooks/usePagination.tsx
client/src/hooks/useQuery.ts
client/src/pages/AdminHomePage/AdminHomePage.tsx
client/src/pages/AdminHomePage/index.ts
client/src/pages/AdminOrdersPage/AdminOrdersPage.tsx
client/src/pages/AdminUserListPage/AdminUserListPage.tsx
client/src/pages/AdminUserListPage/types.d.ts
client/src/routes.tsx

Add usePagination, useQuery hooks and use cases

DASH-137 Add usePagination hook

---

client/src/components/Cart/components/PaymentsBlock.tsx
client/src/components/PurchaseNow/PurchaseNow.tsx
client/src/pages/CartPage/CartPage.tsx
client/src/pages/CheckoutPage/CheckoutPage.tsx
client/src/pages/CheckoutPage/CheckoutPageContext.tsx
client/src/pages/CheckoutPage/components/CheckoutComponent.tsx
client/src/pages/CheckoutPage/components/FioPaymentOption.tsx
client/src/pages/CheckoutPage/components/PaymentOptionComponent.tsx
client/src/pages/CheckoutPage/components/PaymentWallet.tsx
client/src/pages/CheckoutPage/types.d.ts
client/src/pages/PurchasePage/PurchasePageContext.tsx
client/src/pages/PurchasePage/types.d.ts
client/src/types.d.ts
client/src/util/containedFlow.ts
client/src/util/cookies.ts
client/src/util/general.ts
client/src/util/homePage.ts
client/src/util/purchase.ts

- Fix free fio crypto handle purchase

Fix. DASH-99 Free FIO crypto handle purchase

---

server/src/jobs/orders.mjs
server/src/services/orders/WsStatus.mjs

* Move order status update after action in orders job. 
* Add order statusupdate to ws order status.

Order status update fix

---

client/src/constants/purchase.ts
client/src/pages/AdminOrdersPage/components/AdminOrderModal.tsx

* Fix payment received for orders paid with FIO. 
* Set label for status NONE.

DASH-170 Orders deails fixes

---

client/src/components/AddressDomainForm/validation.ts
client/src/components/Modal/Modal.module.scss
client/src/components/Modal/Modal.tsx
client/src/components/PurchaseNow/middleware.ts
client/src/constants/purchase.ts
client/src/pages/AdminOrdersPage/AdminOrdersPage.tsx
client/src/pages/AdminOrdersPage/components/AdminOrderModal/AdminOrderModal.tsx
client/src/pages/AdminOrdersPage/components/AdminOrderModal/AdminOrderModalContext.tsx
client/src/pages/CheckoutPage/components/StripePaymentOption.tsx
client/src/types.d.ts
client/src/utils.ts
server/src/jobs/orders.mjs
server/src/services/orders/Update.mjs
server/src/services/payments/Webhook.mjs

* Admin order history list changes. 
* Fix labels. 
* Change refund and handle fail order in orders job. 
* Refactor order modal.

DASH-195 Update status change messages

---

client/src/types.d.ts
client/src/util/homePage.ts

- Use pre-selected ref domain in AddressWidget form

Hotfix. DASH-176 Pre-selected ref domain

---

client/src/util/validators/is-hash.validator.ts

- Fix sign NFT form validation requirements

Hotfix. DASH-204 Sign NFT form validation

---

client/src/pages/CartPage/CartPageContext.tsx
client/src/pages/CheckoutPage/CheckoutPage.tsx
client/src/pages/CheckoutPage/CheckoutPageContext.tsx
client/src/pages/CheckoutPage/components/CheckoutComponent.tsx

- Handle redirect to fio address selection page on checkout page
- Fix hasLowBalance math operation in cart page

Fix. DASH-175 Minor Stripe release fixes - Checkout redirect

---

client/src/components/ManagePageContainer/ManagePageComponents/SettingsItem.tsx
client/src/pages/CheckoutPage/CheckoutPageContext.tsx

- Fix payment wallet selection in checkout page

Fix. DASH-212 Payment wallet selection issue

---

client/src/pages/PurchasePage/PurchasePageContext.tsx

- Fix purchased action missed button text

Fix. DASH-208 Purchased action button text issue

---

client/src/api/orders.ts
client/src/components/Cart/Cart.tsx
client/src/components/PaymentOptions/PaymentOptions.tsx
client/src/components/PurchaseNow/PurchaseNow.tsx
client/src/components/PurchaseNow/types.d.ts
client/src/pages/CartPage/CartPage.tsx
client/src/pages/CartPage/CartPageContext.tsx
client/src/pages/CheckoutPage/CheckoutPageContext.tsx
client/src/pages/CheckoutPage/components/BeforeSubmitEdgeWallet.tsx
client/src/pages/CheckoutPage/components/CheckoutComponent.tsx
client/src/pages/CheckoutPage/components/FioPaymentOption.tsx
client/src/pages/CheckoutPage/components/PaymentWallet.tsx
client/src/pages/CheckoutPage/components/StripeForm.tsx
client/src/pages/CheckoutPage/components/StripePaymentOption.tsx
client/src/pages/CheckoutPage/types.d.ts
client/src/pages/PurchasePage/styles/PurchasePage.module.scss
client/src/redux/cart/selectors.ts
client/src/redux/fio/selectors.ts
client/src/types.d.ts
server/src/jobs/tx-check.mjs
server/src/services/orders/Update.mjs

* Hide wallet selector on cart page. 
* Add wallet selector on checkout page for both Credit Card and FIO payment option. 
* Update pub key in order on change. 
* Move ledger error message to checkout page.

DASH-211 Notify user when the wallet assignment of private domain is not linked to assigned wallet

---

client/src/components/Cart/Cart.module.scss
client/src/pages/CheckoutPage/CheckoutPageContext.tsx

- Check for cart is empty on checkout redirect

Fix. DASH-175 Fix checkout redirect

---

client/src/pages/AdminOrdersPage/components/AdminOrderModal/AdminOrderModalContext.tsx
server/src/jobs/orders.mjs

* Show item as a domain on fio address custom domain registration history item
* Add error msg to payment record on refund

DASH-195 Custom domain history item

---

client/src/pages/TermsOfServicePage/TermsOfServicePage.tsx

- Add missing space between words

Fix. DASH-178 Add missing space between words

---

server/src/services/orders/Update.mjs
server/src/services/updateOrderStatus.mjs

- Run create purchase confirmation notification after order update
- Fix usdc price to fixed method

Fix. DASH-189 Fix FIO provider purchase confirmation creating notification

---

client/src/pages/AdminOrdersPage/components/AdminOrderModal/AdminOrderModalContext.tsx
client/src/types.d.ts
server/src/jobs/orders.mjs
server/src/models/PaymentEventLog.mjs

* Refactor payment events saving data json. 
* Show tx data when transfering tokens for private domain tx

DASH-195 Token transfer history item 

---

client/src/components/PurchaseNow/PurchaseNow.tsx
client/src/components/PurchaseNow/index.ts
client/src/pages/PurchasePage/PurchasePageContext.tsx

- Fix FIO partial success remove registered items on retry
- Create order params and free order params util
- Use create order params on cart and checkout pages
- Create new order on FIO purchase retry

Fix. DASH-239 Succeed cart items not removed on partial success

---

client/src/api/fio.ts

- Handle 0 row id value in availCheckTableRows

Fix. DASH-146 Handle 0 row id value in availCheckTableRows

---

client/src/components/SignNft/SignNft.tsx
client/src/pages/HomePage/HomePage.tsx
client/src/redux/containedFlow/sagas.ts
client/src/redux/fio/reducer.ts
client/src/redux/fio/selectors.ts
client/src/redux/sagas.ts
client/src/services/ContainedFlow.tsx

- Fix contained flow homepage redirect loop issue
- Fix contained flow set registration and action steps for sign nft
- Check for current wallet in SignNft component

Fix. DASH-294 Contained flow fixes

---

client/src/redux/containedFlow/sagas.ts
client/src/redux/profile/sagas.ts
client/src/services/ContainedFlow.tsx

- Fix REG contained flow redirect issues
- Fix opened sign in modal window when is new user

Fix. DASH-294 Contained flow REG action redirect issues

---

server/src/migrations/20221017095320-update-chain-codes-list.js

- "Binance Coin" => "Binance Chain"
- "BSC FARM" => "Binance Smart Chain"

Update. DASH-143 Update Binance chain code names in a database

---

server/src/services/updateOrderStatus.mjs
server/src/utils/order.mjs

- fix countTotalPriceAmount entry values, 
- fix handleOrderPaymentInfo total price

Fix. DASH-95 Fix purchased email sending

---

client/src/components/ChainAndTokenCodesAutocompleteFields/ChainAndTokenCodesAutocompleteFieldsContext.tsx
client/src/components/Input/styles/EditableSelect.module.scss
client/src/components/SignNft/components/SignNftForm/SignNftForm.tsx
server/src/models/ChainCode.mjs

- Enable chain code and token code search with label value
- Fix long words in dropdown
- Make sign NFT chain codes input values uppercased

Update. DASH-332 Enable chain code and token code search by label

---

client/src/components/Input/ErrorBadge.tsx
client/src/pages/AddTokenPage/copmonents/AddTokenInput.tsx

- Hide title for FIO:FIO error message in token list, add title and hideErrorTitle props into ErrorBadge

Fix. DASH-318 Fix Token List FIO:FIO error message

---

client/src/components/ChainAndTokenCodesAutocompleteFields/ChainAndTokenCodesAutocompleteFieldsContext.tsx
client/src/components/Input/ChainCodeCustomDropdown.tsx
client/src/components/Input/EditableSelect/EditableSelect.tsx
client/src/pages/NftValidationPage/components/ContractAddressField.tsx

- Add onBlur for ContractAddressField in NFT Validation page
- Add onBlur check before call it in EditableSelect
- Fix hasError logic for ChainCodeCustomDropdown
- Wrap onBlur function into useCallback

Fix. DASH-318 Fix error logic

---

client/src/util/containedFlow.ts

- Make non required chain code and contract address params for sign NFT flow

Updates. DASH-378 Sign NFT contained flow without required params

---

client/src/pages/DashboardPage/DashboardListItem.tsx
client/src/pages/DashboardPage/DashboardPage.module.scss
client/src/pages/DashboardPage/DashboardPage.tsx
client/src/pages/WalletPage/WalletPage.tsx
client/src/pages/WalletPage/styles/WalletPage.module.scss
client/src/pages/WalletsPage/components/Title.tsx
client/src/pages/WalletsPage/styles/Title.module.scss
client/src/pages/WalletsPage/styles/WalletItem.module.scss

- Show wallet's names on dashboard page for mobile view, UI style fixes
-  Fix wallet name action buttons UI

Fix. DASH-366 Show wallets names at Dashboard page mobile view

---

client/src/components/FioTokensReceive/FioTokensReceive.module.scss
client/src/services/Ref.tsx

- Fix affiliate input ref link padding
- Always redirect to domain landing page on ref affiliate link

Fix. DASH-222 Domain sales fixes

---

client/src/components/FioTokensReceive/FioTokensReceive.module.scss
client/src/services/Ref.tsx

Reverts fioprotocol/fio-dashboard#888

Revert "Fix. DASH-222 Domain sales fixes"

---

client/src/components/BitPayButton/BitPayButton.tsx
client/src/pages/CheckoutPage/components/BitpayPaymentOption.tsx
server/src/external/payment-processor/bitpay.mjs

- Fix loader and disabling BitPay checkout button
- Fix cancel BitPay invoice method

Updates. DASH-257 BitPay updates

---

server/src/external/payment-processor/bitpay.mjs

Reverts fioprotocol/fio-dashboard#899

Revert "Fix. DASH-257 Debug BitPay client token issue"

---

client/src/components/BitPayButton/BitPayButton.tsx
client/src/components/common/SubmitButton/SubmitButton.tsx
client/src/pages/CheckoutPage/components/BitpayPaymentOption.tsx
client/src/pages/SettingsPage/components/ChangePin/ChangePin.tsx
client/src/pages/SettingsPage/components/ChangePin/ChangePinForm.tsx
client/src/pages/SettingsPage/components/ChangePin/types.d.ts
client/src/types.d.ts
server/src/services/orders/Update.mjs
server/src/utils/order.mjs

- Fix handle refund non fio payment processor with fio tokens amount
- Fix redirect bitpay issue, fix private domain fch transaction for bitpay for dashboard
- Move ClickEventTypes into main type.d.ts file

Fix. DASH-434 BitPay issues fixes

---

client/src/components/ConnectWallet/FeesModal/FeesModalInput.module.scss
client/src/components/ConnectWallet/FeesModal/FeesModalInput.tsx
client/src/pages/UnwrapDomainPage/styles/UnwrapDomainForm.module.scss

- Remove border from fees input
- Set default transaction fee fro unwrap
- Fix transaction fees title on domain unwrap page

Fix. DASH-452 Unwrap issues fixes

---

client/src/components/PurchaseNow/PurchaseNow.tsx
client/src/components/PurchaseNow/index.ts
client/src/components/PurchaseNow/types.d.ts
client/src/pages/CheckoutPage/CheckoutPageContext.tsx

- Load user's profile on checkout page leave, don't load it after items register

Hotfix. DASH-459 Fix purchase cart analytics

---

client/src/components/Input/Input.module.scss
client/src/components/Input/InputActionButtons.module.scss
client/src/components/Input/InputActionButtons.tsx
client/src/components/Input/TextInput.tsx
client/src/pages/FioAddressSelectionPage/FioAddressSelectionPageContext.tsx
client/src/pages/FioAddressSelectionPage/components/ActionButton/ActionButton.tsx
client/src/pages/FioAddressSelectionPage/components/AdditionalItemsList/AdditionalItemsList.tsx
client/src/pages/FioAddressSelectionPage/components/FioAddressSelectionComponent/FioAddressSelectionComponent.tsx
client/src/pages/FioAddressSelectionPage/components/SuggestedItemsList/SuggestedItemsList.tsx
client/src/pages/FioAddressSelectionPage/components/UsersItemsList/UsersItemsList.module.scss
client/src/pages/FioAddressSelectionPage/components/UsersItemsList/UsersItemsList.tsx
client/src/pages/FioAddressSelectionPage/types.d.ts
client/src/redux/registrations/selectors.ts
client/src/types.d.ts
client/src/util/fio.ts

Feature. DASH-480 Add analytics

---

client/src/pages/FioDomainSelectionPage/FioDomainSelectionPageContext.tsx
client/src/pages/FioDomainSelectionPage/components/DomainSelectionComponent/DomainSelectionComponent.tsx

- Fix period
- Fix show error badge

Fix. DASH-481 Domain selection page fixes

---

client/src/pages/FioDomainSelectionPage/FioDomainSelectionPageContext.tsx
client/src/pages/FioDomainSelectionPage/components/DomainSelectionComponent/DomainSelectionComponent.tsx

- Don't validate on selected or period changes
- Handle selected suggested domain

Fix. DASH-509 Fix selected domain issue. 

---

client/src/components/AddressDomainFormContainer/AddressDomainFormContainer.tsx
client/src/components/Input/Input.module.scss
client/src/components/SelectionItem/components/AddToCartButton/AddToCartButton.module.scss
client/src/components/SelectionItem/components/AddToCartButton/AddToCartButton.tsx
client/src/pages/FioAddressSelectionPage/FioAddressSelectionPageContext.tsx
client/src/pages/FioAddressSelectionPage/components/FioAddressSelectionComponent/FioAddressSelectionComponent.module.scss
client/src/pages/FioDomainSelectionPage/FioDomainSelectionPageContext.tsx

- Fix add to cart button icon height
- Fix domain error handling
- Fix FioAddressSelectionComponent container layout
- Fix loading state on FCH and domain selection page. Update style for loader icon in input.
- Don't run validation on adding FCH item to cart

Fix. DASH-480 FCH selection page input issues

---

client/src/api/responses.d.ts
client/src/components/ManagePageContainer/ManagePageComponents/ActionButtons.tsx
client/src/pages/FioAddressCustomSelectionPage/FioAddressCustomSelectionPage.tsx
client/src/pages/FioAddressCustomSelectionPage/FioAddressCustomSelectionPageContext.tsx
client/src/pages/FioAddressCustomSelectionPage/components/SelectedItemComponent/SelectedItemComponentContext.tsx
server/src/models/ReferrerProfile.mjs
server/src/services/registration/DomainsList.mjs

- Handle free FCH partner domains on custom FCH form
- Set closed initial dropdown on custom FCH form when go from domains list page

Fix. DASH-521 handle free FCH on custom ending

---

client/src/pages/AdminDefaultsPage/components/AvailableDomains.tsx
client/src/pages/AdminDefaultsPage/components/DashboardDomains.tsx
client/src/pages/AdminDefaultsPage/components/SearchPostfixes.tsx
client/src/pages/AdminDefaultsPage/components/SearchPrefixes.tsx
client/src/pages/AdminDefaultsPage/components/UsernamesOnCustomDomains.tsx
client/src/pages/AdminOrdersPage/AdminOrdersPage.tsx
client/src/pages/AdminRegularUserDetailsPage/components/UserOrders.tsx

Please, DO NOT squash.
https://fioprotocol.atlassian.net/browse/DASH-523
https://fioprotocol.atlassian.net/browse/DASH-524
https://fioprotocol.atlassian.net/browse/DASH-516

Admin fixes

---

client/src/pages/FioAddressCustomSelectionPage/components/SelectedItemComponent/SelectedItemComponentContext.tsx
server/src/config/constants.js
server/src/jobs/orders.mjs
server/src/models/Order.mjs

- Fix fallback usage condition
- Fix crashing add custom FCH page on ref user

Fix. DASH-553 fix fallback for FCH

---

client/src/components/CreateAccountForm/CreateAccountForm.tsx
client/src/components/CreateAccountForm/EmailPassword.tsx
client/src/components/Input/Input.tsx

- Fix email and confirm email fields behaviour

Fix. DASH-188 Streamline registration and purchase flow fixes

---

server/src/jobs/wallet-data.mjs

Reverts fioprotocol/fio-dashboard#1070

Revert "Hotfix. Remove send email for wallet balance change"

---

client/src/components/CreateAccountForm/CreateAccountForm.tsx
client/src/components/CreateAccountForm/index.ts

- HOTFIX with pin code on create account

Develop > Staging [Release 1.11][HOTFIX]

---

server/src/services/emailSender.mjs

For the email generated by the Dashboard replaced text “on profile null” on “on FIO”.

DASH-563 change null on email

---

client/src/components/Cart/Cart.tsx
client/src/components/MainHeader/components/LoggedNav.tsx
client/src/components/MainHeader/components/Navigation.tsx
client/src/components/MainHeader/index.ts
client/src/components/MainHeader/types.d.ts
client/src/pages/CartPage/CartPage.tsx
client/src/pages/CartPage/CartPageContext.tsx
client/src/pages/PurchasePage/PurchasePage.tsx
client/src/pages/PurchasePage/PurchasePageContext.tsx
client/src/redux/cart/actions.ts
client/src/redux/cart/reducer.ts
client/src/redux/cart/selectors.ts
client/src/redux/store.ts
server/src/services/emailSender.mjs

- when purchase button clicked and we are redirected to purchase page (all success) → cart button will be hidden 
- then if user clicks to close, and payment is in progress (not other statuses) → clear the cart and unhide it
- when purchase failed/success/partially success/cancelled →  unhide cart

DASH-573: cart not emptied

---

client/src/api/fio.ts

- Use default proxy list on get proxy error

Hotfix. DASH-592 staking proxy list

---

client/src/services/AutoLogout.tsx

DASH:586: cart expiration added

---

client/src/components/AddressDomainCart/AddressDomainCart.tsx
client/src/components/Cart/Cart.tsx
client/src/pages/CartPage/CartPage.tsx
client/src/pages/PurchasePage/PurchasePageContext.tsx
client/src/redux/cart/actions.ts
client/src/redux/cart/sagas.ts

DASH-573: cart refactor

---

client/src/components/AddressDomainCart/AddressDomainCart.tsx
client/src/components/Cart/Cart.tsx
client/src/components/MainHeader/components/Navigation.tsx
client/src/components/MainHeader/index.ts
client/src/components/MainHeader/types.d.ts
client/src/pages/CartPage/CartPage.tsx
client/src/pages/CartPage/CartPageContext.tsx
client/src/pages/PurchasePage/PurchasePageContext.tsx
client/src/redux/cart/actions.ts
client/src/redux/cart/reducer.ts
client/src/redux/cart/selectors.ts
client/src/redux/store.ts
client/src/services/AutoLogout.tsx
server/src/jobs/wallet-data.mjs

- isHidden Removed
- oldCart Implemented

feature/DASH:597: old cart items implementation

---

client/src/assets/images/checked-circle.svg
client/src/components/Badge/Badge.module.scss
client/src/components/NotificationBadge/NotificationBadge.module.scss
client/src/components/NotificationBadge/NotificationBadge.tsx
client/src/components/Notifications/Notifications.tsx
client/src/components/PasswordRecoveryForm/PasswordRecoveryForm.tsx
client/src/constants/notifications.ts
client/src/redux/profile/sagas.ts
client/src/types.d.ts
server/src/models/Notification.mjs
server/src/services/notifications/List.mjs
server/src/services/users/Create.mjs
server/src/services/users/Info.mjs
server/src/services/users/SetRecovery.mjs

- Add new UI to NotificationBadge
- Update Create Account notification. Handle auto close.
- Remove Recovery notifications from app
- Update new UI NotificationBadge check icon

Feature. DASH-415 Redesign Dashboard page

---

client/src/pages/FioTokensGetPage/FioTokensGetPage.tsx

- Removing liquid logo from list

DASH-522: removing liquid logo

---

client/src/pages/StakeTokensPage/components/StakeTokensForm/StakeTokensForm.tsx
client/src/pages/UnstakeTokensPage/components/UnstakeTokensForm/UnstakeTokensForm.tsx

- Removing duplicate error.
- Changing the color to danger.

DASH-533: doubled error removed

---

client/src/pages/CartPage/CartPageContext.tsx
client/src/pages/FioAddressSelectionPage/FioAddressSelectionPageContext.tsx
client/src/pages/PurchasePage/PurchasePageContext.tsx

Reverts fioprotocol/fio-dashboard#1096

Revert "DASH-580: loading user profiles"

---

client/src/components/Footer/Footer.tsx
client/src/components/Footer/components/NavComponent.tsx
client/src/constants/labels.ts
client/src/hooks/useMaintenance.ts
client/src/pages/MainLayout/MainLayout.tsx
client/src/routes.tsx

- Modals hidden
- Navigation hidden
- Page title fixed
- Loading added

DASH-577: implementing outage fixes

---

client/src/util/analytics.ts

• fixing analytics log for free_fch

DASH-594: fixing log of free fch

---

client/src/pages/AdminDefaultsPage/components/DashboardDomains.tsx
client/src/util/cart.ts
server/src/migrations/20230324083055-set-domains-to-lowercase.js

-  Fix double add cart item to cart

Fix. DASH-558 Fix double add cart item to cart

---

client/src/pages/FioAddressSelectionPage/FioAddressSelectionPageContext.tsx

User was able to add free FCH to cart even when he already owns one.

DASH-580: free fch readd fix

---

client/src/components/AddressDomainCart/AddressDomainCart.module.scss
client/src/pages/CartPage/CartPageContext.tsx
client/src/pages/FioAddressCustomSelectionPage/components/SelectedItemComponent/SelectedItemComponentContext.tsx
client/src/pages/FioAddressSelectionPage/FioAddressSelectionPageContext.tsx
client/src/util/cart.ts
client/src/util/fio.ts

- Fix total price on custom domain delete
- Fix long names in a right side small cart
- Fix period for adding fch with custom domain from custom selection page
- Fix domain item and fch with the same custom domain merge in cart

Fix. DASH-606 Add items to cart logic fixes

---

client/src/pages/FioAddressCustomSelectionPage/FioAddressCustomSelectionPageContext.tsx
client/src/pages/FioAddressCustomSelectionPage/components/SelectedItemComponent/SelectedItemComponentContext.tsx
client/src/util/analytics.ts
client/src/util/cart.ts

- Fix combo items fch+domain analytics

Fix. DASH-604 Fix combo items fch+domain analytics

---

client/src/pages/CartPage/CartPageContext.tsx
client/src/pages/CheckoutPage/CheckoutPageContext.tsx
client/src/util/cart.ts

- Fix multi year FCH price on checkout page
- Fix leak warning on cart page hook

Fix. DAH-589 Multi year custom FCH fixes

---

client/src/redux/cart/sagas.ts

Fixed double cart_emptied issue

DASH-607: Double cart empty fixed

---

client/src/api/index.ts
package.json
server/src/external/fio.mjs
server/src/services/external/Prices.mjs

- Handle fio sdk error on client and backend side
- Return an error if there is no prices on a backend

Fix. DASH-584 random shows of default errors modal

---

client/src/constants/vars.ts
client/src/hooks/useMaintenance.ts
client/src/routes.tsx

- Addint 5sec checker for maintenance
- Route fixes

DASH-577: UAT fixes added

---

client/src/constants/fio.ts
client/src/redux/edge/actions.ts

DASH-590: Checking the edge wallet naming

---

client/src/components/AddressWidget/AddressWidget.tsx
client/src/components/AddressWidget/components/FormComponent/FormComponent.tsx
client/src/components/NotificationBadge/NotificationBadge.module.scss
client/src/components/NotificationBadge/NotificationBadge.tsx
client/src/constants/regExps.ts
client/src/constants/twitter.ts
client/src/pages/TwitterPage/TwitterPage.module.scss
client/src/pages/TwitterPage/TwitterPage.tsx
client/src/types.d.ts

DASH-612: fixes added

---

client/src/api/health-check.ts
client/src/api/index.ts
client/src/api/responses.d.ts
client/src/api/twitter.ts
client/src/components/TweetShare/TweetShare.module.scss
client/src/constants/twitter.ts
client/src/pages/TwitterPage/TwitterPage.module.scss
client/src/pages/TwitterPage/TwitterPage.tsx
server/src/router.mjs

- When user edits the handle (just clicking into field is not enough), the Verified banner disappears and user has to verify again
- When user edits the handle back to a one that was just verified, the Verified banner re-appears
- Cookie Checking
- Locking implementation on UI
- UI Refactor

feature/DASH-614: Special cases handling

---

client/src/api/client.ts
server/src/app.mjs
server/src/middlewares.mjs

Call superagent with credentials. 
Set cors origin to true. 
Move cooikes part before endpoint in app

Fix. DASH-642 Fix sending cookies from server

---

client/src/hooks/useMaintenance.ts

DASH-648: page delay fix

---

client/src/pages/TwitterPage/TwitterPage.tsx

DASH-614: verified banner fix

---

client/src/pages/TwitterPage/TwitterPage.tsx

DASH-649: undescores fix

---

client/public/index.html
client/src/app.tsx
client/src/pages/TwitterPage/TwitterPage.tsx
package.json

DASH-647: react snap setted up

---

client/package.json
client/public/index.html
client/src/routes.tsx
client/src/util/general.ts
package.json

- twitter-handle prerender added

DASH-647: twitter-handle page prerender

---

client/src/components/PurchaseNow/PurchaseNow.tsx
client/src/components/PurchaseNow/middleware.ts

- Fix for free private domain registration

Develop > Staging [Release 1.13][Twitter][Fixes]

---

client/src/components/TweetShare/TweetShare.tsx
client/src/pages/TwitterPage/TwitterPage.tsx

DASH-662: fix url

---

client/src/components/AddressWidget/AddressWidget.module.scss
client/src/components/AddressWidget/AddressWidget.tsx
client/src/components/NotificationBadge/NotificationBadge.module.scss
client/src/components/NotificationBadge/NotificationBadge.tsx
client/src/components/TweetShare/TweetShare.tsx
client/src/constants/twitter.ts
client/src/pages/TwitterPage/TwitterPage.tsx

DASH-664: steps added

---

client/src/components/PaymentOptions/PaymentOptions.tsx

DASH-616: hide button instead of hidden

---

client/src/pages/TwitterPage/TwitterPage.tsx

- Fix twitter verify steps. 
- Disallow to user to add other twitter fch after verification

Fix. DASH-666 Fix twitter fch on change issue.

---

client/src/components/PurchaseNow/components/PurchaseEdgeWallet.tsx
client/src/pages/OrderDetailsPage/components/OrderItem/OrderItem.tsx
client/src/util/purchase.ts

- Fix multi domain renew for FIO payment provider
- Remove unused transformPurchaseResults util method

Fix. DASH-660 Multi domain fix

---

server/src/jobs/wrap-status.mjs
server/src/models/WrapStatusFioUnwrapNftsLogs.mjs
server/src/models/WrapStatusFioUnwrapNftsOravotes.mjs
server/src/models/WrapStatusFioUnwrapTokensLogs.mjs
server/src/models/WrapStatusFioUnwrapTokensOravotes.mjs

- Force update oravotes for unwrap domains/tokens if all approved exist.
- Increase UNWRAP_RETRIES_LIMIT to 5

Fix. DASH-640 Force update approved voters for unwrap domains/tokens

---

client/src/api/fio.ts
client/src/constants/fio.ts
client/src/pages/CheckoutPage/CheckoutPageContext.tsx
client/src/pages/FioAddressCustomSelectionPage/components/SelectedItemComponent/SelectedItemComponentContext.tsx
client/src/types.d.ts
client/src/util/validators/fio-address-custom-domain.validator.ts

- Change return getTableRaw params. Now returns more and rows.
- Fetch all proxies using recursive

Updates. DASH-661 Fetch all proxies

---

package.json

Reverts fioprotocol/fio-dashboard#1236

Revert "DASH-673 Update FIO SDK to develop branch"

---

client/src/components/PurchaseNow/components/PurchaseEdgeWallet.tsx
client/src/constants/fio.ts

Possible were issues with public keys.

Fix. DASH-660 Use registerOwnerFioDomain on FIO purchase for domains. 

---

client/src/components/PurchaseNow/components/PurchaseEdgeWallet.tsx
package.json

Fix. DASH-660 multiple year fio issue

---

client/src/util/analytics.ts
server/src/services/updateOrderStatus.mjs

- change REACT_APP_GOOGLE_TAG_MANAGER_ID into REACT_APP_GOOGLE_ANALYTICS_ID in getGASessionId for getting ga session
- convert item  prices to numbers

Fix. DASH-699 Fix ga analytics

---

client/src/util/analytics.ts
server/src/services/updateOrderStatus.mjs

Staging > Main [Release 1.14][Hotfix]

---

client/src/components/ManagePageContainer/ManagePageContainer.module.scss
client/src/components/ManagePageContainer/ManagePageContainer.tsx
client/src/components/ManagePageContainer/components/SettingsItem/SettingsItem.tsx
client/src/pages/FioDomainManagePage/FioDomainManagePage.tsx
client/src/pages/FioDomainManagePage/FioDomainManagePageContext.tsx
client/src/pages/FioDomainManagePage/components/WatchListDomainsComponent/WatchListDomainsComponent.tsx

- Fix warning badge UI margins
- Add Are you sure modal for removing domain from watchlist

Fix. DASH-779 Whatchlist issues

---

client/src/components/LayoutContainer/LayoutContainer.module.scss
client/src/components/ManagePageContainer/ManagePageContainer.module.scss
client/src/pages/WalletPage/styles/WalletPage.module.scss
client/src/pages/WalletsPage/components/TotalBalanceBadge.tsx
client/src/pages/WalletsPage/styles/TotalBalanceBadge.module.scss

- Layout, ManagePage, WalletPage UI fixes.
- Update and fix TotalBalanceBadge component.

Fix. DASH-787 Fix TotalBalanceBadge component

---

client/src/components/InfiniteScroll/InfiniteScroll.tsx
client/src/components/Loader/Loader.tsx
client/src/components/Tabs/Tabs.tsx
client/src/pages/WalletPage/WalletPage.tsx
client/src/pages/WalletPage/WalletPageContext.tsx
client/src/pages/WalletPage/components/FioObtDataTab.tsx
client/src/pages/WalletPage/components/FioRecordsList.tsx
client/src/pages/WalletPage/components/FioRequestsTab.tsx
client/src/pages/WalletPage/components/WalletTabs.tsx

- Fix fio requests items oreder.
- Fix publicKey param after autologout on wallet page.

Fix. DASH-804 Fix request show reverse issue. Fix publicKey issue after logout on wallet page.

---

client/public/index.html
client/src/app.tsx
client/src/components/CreateAccountForm/CreateAccountForm.tsx
client/src/components/CreateAccountForm/index.ts
client/src/hooks/googleTagManager.ts
package.json

- Defer load of GTM and BitPay scripts
- Remove unused react-router-last-location library
- Add analyzer for bundle debug

Feature. DASH-564 Performance improvements

---

client/src/components/ManagePageContainer/ManagePageContainer.tsx
client/src/components/ManagePageContainer/ManagePageContainerContext.tsx
client/src/components/ManagePageContainer/components/ActionButtons/ActionButtons.module.scss
client/src/components/ManagePageContainer/components/ActionButtons/ActionButtons.tsx
client/src/components/ManagePageContainer/components/DateComponent/DateComponent.tsx
client/src/components/ManagePageContainer/components/ItemCopmonent/ItemComponent.tsx
client/src/components/ManagePageContainer/components/ItemsScreenView/DesktopView.tsx
client/src/components/ManagePageContainer/components/ItemsScreenView/MobileView.tsx
client/src/components/ManagePageContainer/components/ItemsScreenView/UIView.module.scss
client/src/components/ManagePageContainer/components/SettingsItem/SettingsItem.tsx
client/src/components/ManagePageContainer/types.d.ts
client/src/constants/regExps.ts
client/src/pages/FioDomainManagePage/FioDomainManagePage.tsx
client/src/pages/FioDomainManagePage/FioDomainManagePageContext.tsx
client/src/pages/FioDomainManagePage/components/WatchListDomainsComponent/WatchListDomainsComponent.module.scss
client/src/util/fio.ts

- Handle expiration domain before 30 days.
- Show warning icons on domain/fch items on mobile UI. 
- UI Fixes for mobile wrap and add to watchlist buttons.

Feature. DASH-663 Handle expiration domain updates.

---

client/src/api/general.ts
client/src/landing-pages/fio-id-landing-page/FioIdLandingPage/components/NftsTabComponent/NftsTabComponentContext.tsx
server/src/router.mjs
server/src/routes/general.mjs
server/src/services/general/GetUrlContent.mjs

- Handle infura ipfs links.
- Create getUrlContent.
- Use getUrlContent for non loadable images like svg html code.

Fix. DASH-813 Fix NFT metadata image urls.

---

client/src/components/PurchaseNow/components/PurchaseEdgeWallet.tsx

- Add timeout between add bundles for the same fio handle
- Change timeout between domain and register domain register for the same fio handle

Fix. DASH-864 Add bundles issue

---

client/src/pages/RefHomePage/RefHomePageContext.tsx
server/src/constants/moralis-chains.mjs
server/src/external/moralis.mjs
server/src/services/metamask/NftTokenVerification.mjs

- Enable to pass contract address to moralis get nfts.
- Make case insesitive of token_address on metamask verification.
- Remove chain verification on client side.

Fix. DASH-842 Gated Registration metamask verification fixes.

---

client/src/components/Input/Input.module.scss
client/src/components/Input/TextInput.tsx
client/src/constants/fio.ts
client/src/landing-pages/fio-wallet-snap-landing-page/FioWalletSnapComponent/FioActionForms/CustomActionForm.tsx
client/src/landing-pages/fio-wallet-snap-landing-page/FioWalletSnapComponent/FioActionForms/FioActionForms.tsx
client/src/landing-pages/fio-wallet-snap-landing-page/FioWalletSnapComponent/FioActionForms/StakeFioTokens.tsx
client/src/landing-pages/fio-wallet-snap-landing-page/FioWalletSnapComponent/FioActionForms/TransferFioDomain.tsx
client/src/landing-pages/fio-wallet-snap-landing-page/FioWalletSnapComponent/FioActionForms/TransferFioHandle.tsx
client/src/landing-pages/fio-wallet-snap-landing-page/FioWalletSnapComponent/FioActionForms/TransferFioTokens.tsx
client/src/landing-pages/fio-wallet-snap-landing-page/FioWalletSnapComponent/FioActionForms/UnstakeFioTokens.tsx
client/src/landing-pages/fio-wallet-snap-landing-page/FioWalletSnapComponent/FioWalletSnapComponentContext.tsx
client/src/landing-pages/fio-wallet-snap-landing-page/FioWalletSnapComponent/constants.ts

- Add more FIO actions to snap UI page

Feature. DASH-853 implement snap UI

---

client/src/components/LoginForm/UsernamePassword.tsx
client/src/components/LoginForm/components/MetamaskLogin/MetamaskLogin.module.scss
client/src/components/LoginForm/components/MetamaskLogin/MetamaskLogin.tsx
client/src/components/LoginForm/components/MetamaskLogin/MetamaskLoginContext.tsx
client/src/redux/profile/reducer.ts

- Handle is MetaMask installed or not on sign in modal.
- Add loader on Metamask login.
- Clear alternative login error on sign in modal close.

Feature. DASH-854 Alternate authenticate

---

client/src/components/LoginForm/components/MetamaskLogin/MetamaskLogin.module.scss
client/src/components/LoginForm/components/MetamaskLogin/MetamaskLogin.tsx
client/src/components/MetamaskConfirmAction/MetamaskConfirmAction.tsx
client/src/components/MetamaskConfirmAction/index.ts
client/src/components/Modal/MetamaskConnectionModal/MetamaskConnectionModal.module.scss
client/src/components/Modal/MetamaskConnectionModal/MetamaskConnectionModal.tsx
client/src/components/Modal/MetamaskConnectionModal/index.ts
client/src/pages/FioDomainStatusChangePage/FioDomainStatusChangePage.tsx
client/src/pages/FioDomainStatusChangePage/components/FioDomainStatusChangeMetamaskWallet.tsx
client/src/redux/fio/selectors.ts

- Update Metamask connection modal. Handle errors.
- Create Metamask confirmation action component.
- Add change domain status action for Metamask.

Feature. DASH-906 Alternative sign transactions

---

client/src/pages/CancelFioRequestPage/CancelFioRequestPage.tsx
client/src/pages/CancelFioRequestPage/components/CancelRequestMetamaskWallet.tsx
client/src/pages/RejectFioRequestPage/RejectFioRequestPage.tsx
client/src/pages/RejectFioRequestPage/components/RejectRequestMetamaskWallet.tsx
client/src/types/fio.d.ts

- Add cancel and reject fio request actions for metamask wallet.

Feature. DASH-906 Alternative sign transactions.

---

client/src/pages/EditTokenPage/EditTokenPage.tsx
client/src/pages/EditTokenPage/EditTokenPageContext.tsx
client/src/pages/EditTokenPage/components/EditTokenMetamaskWallet.tsx

- Add edit tokens action for metamask wallet.

Feature. DASH-906 Alternative transactions.

---

client/src/components/MainHeader/components/Navigation.tsx
client/src/pages/TwitterPage/TwitterPage.tsx
client/src/pages/WalletPage/components/WalletSettings.tsx
client/src/pages/WalletsPage/components/CreateWallet/CreateMetamaskWallet.tsx
client/src/pages/WalletsPage/components/CreateWallet/CreateWallet.tsx

- Hide Create Account button if user has MetaMask or Opera wallets installed.
- Fix misspelling on delete MetaMask wallet warning message.
- Change logic for derivation index on create MetaMask wallet. Increment last one.
- Fix step change on Twitter page if FIO handle already exists.

Fix. DASH-854 Alternative auth fixes

---

client/src/assets/images/metamask-landing/faq-background.svg
client/src/assets/styles/colors.scss
client/src/pages/MetamaskLandingPage/MetamaskLandingPage.tsx
client/src/pages/MetamaskLandingPage/MetamaskLangingPage.module.scss

- Add FAQ section for MetaMask landing page.
- Fix gap between info items in MetaMask landing page.

Feature. DASH-924 Add FAQ section MetaMask landing page.

---

client/src/pages/MetamaskLandingPage/MetamaskLandingPage.tsx
client/src/pages/MetamaskLandingPage/MetamaskLandingPageContext.tsx
client/src/pages/MetamaskLandingPage/MetamaskLangingPage.module.scss
client/src/services/MetamaskSnap.tsx
client/src/util/snap.ts

- Add logic to MetaMask landing page action buttons.

Feature. DASH-912 MetaMask landing page add logic to action button

---

client/src/assets/images/metamask-landing/faq-background.svg
client/src/assets/styles/colors.scss
client/src/hooks/usePagination.tsx
client/src/pages/MetamaskLandingPage/MetamaskLandingPage.tsx
client/src/pages/MetamaskLandingPage/MetamaskLangingPage.module.scss
server/src/services/users/Delete.mjs

- Add FAQ section to MetaMask Landing page
- Fix UI for big screens and other UI fixes on MetaMask Landing Page
- Fix react keys warning on Admin Orders Page
- Destroy DomainWatchList on user delete

Develop > Staging [MetaMask Landing Page fixes release]

---

client/src/api/cart.ts
client/src/components/Badges/PayWithBadge/PayWithBadge.module.scss
client/src/constants/queryParams.ts
client/src/pages/CheckoutPage/CheckoutPageContext.tsx
client/src/pages/CheckoutPage/components/StripeForm.tsx
client/src/pages/CheckoutPage/components/StripePaymentOption.tsx
client/src/pages/CheckoutPage/constants.ts
client/src/redux/cart/actions.ts
client/src/redux/cart/reducer.ts
client/src/util/purchase.ts
server/src/router.mjs
server/src/routes/cart.mjs
server/src/services/cart/GetUsersCart.mjs

- Handle return url for stripe payments.
- Fix wallet selection UI on Checkout page.

Feature. DASH-932 Stripe status updates

---

client/src/pages/CartPage/CartPageContext.tsx
client/src/pages/CheckoutPage/CheckoutPageContext.tsx
client/src/services/AutoLogout.tsx

- Fix redirect on Checkout page
- Fix infinite loader on cart error
- Handle create order error if no cart on database
- Don't clear cart on Stripe redirect and user should be logged out automatically.

Fix. DASH-932 Fix checkout redirect on stripe return url

---

client/src/components/CustomDropdown/CustomDropdown.module.scss
client/src/components/CustomDropdown/CustomDropdown.tsx
client/src/pages/FioAffiliateProgramLandingPage/components/AffiliateSelectFCHModal.tsx
client/src/pages/FioAffiliateProgramLandingPage/components/FAQSection.tsx
client/src/pages/FioAffiliateProgramLandingPage/components/LinksSection.tsx
client/src/pages/FioAffiliateProgramLandingPage/styles/FAQSection.module.scss
client/src/pages/FioAffiliateProgramLandingPage/styles/LinksSection.module.scss
client/src/pages/FioAffiliateProgramPage/FioAffiliateProgramPage.tsx
client/src/pages/FioAffiliateProgramPage/FioAffiliateProgramPageContext.tsx
client/src/pages/FioAffiliateProgramPage/components/AffiliateModal.tsx
client/src/pages/FioAffiliateProgramPage/styles/FioAffiliateProgramPage.module.scss
client/src/pages/FioAffiliateProgramPage/types.d.ts

- Update affiliate content page.
- Fix UI bugs.

DASH-936 Update affiliate content page. Fix UI bugs.

---

server/src/migrations/20240112173612-add-userProfileType-to-user-table.js
server/src/models/User.mjs

Change add-userProfileType-to-user-table migration. Use STRING type instead of enum.

Migration hot fix.

---

client/src/components/PaymentOptions/PaymentOptions.tsx
client/src/components/PaymentOptions/components/PaymentButton.tsx
client/src/pages/CheckoutPage/components/BitpayPaymentOption.tsx
client/src/redux/profile/sagas.ts

- Fix type on hasRedirectTo for alternative login
- Fix BitPay button loader
- Fix BitPay redirect issue

Fix. DASH-953 BitPay issue

---

client/src/pages/AdminRegularUserDetailsPage/AdminRegularUserDetailsPage.tsx
client/src/pages/AdminRegularUsersListPage/AdminRegularUsersList.tsx
client/src/pages/AdminRegularUsersListPage/AdminRegularUsersListContext.tsx
client/src/pages/AdminSearchResultPage/components/AdminOrdersSearchResult.tsx
client/src/redux/admin/sagas.ts

1. Added user id to:
- Search results
- Users list
- User detailed info
- Order's list export pdf
- User's list export pdf
2. Added link to user details on search results

DASH-956 Add user id where no email to admin pages.

---

package.json
server/src/jobs/emails.mjs
server/src/jobs/wallet-data.mjs
server/src/models/User.mjs
server/src/services/updateOrderStatus.mjs

- Do not send email if no user email
- Do not create notifications if no user email

Fix. DASH-957 Do not send email if no user email

---

client/src/pages/AdminPartnersListPage/AdminPartnersListPage.tsx
client/src/pages/AdminPartnersListPage/components/updatePartner/PartnerFormComponent.tsx
client/src/pages/AdminPartnersListPage/components/updatePartner/PartnerFormDomainRow.tsx
client/src/pages/RefHomePage/RefHomePageContext.tsx
client/src/types.d.ts
client/src/util/homePage.ts
server/src/migrations/20240322175650-remove-preselected-domain-from-partner-profile-settings.js
server/src/models/ReferrerProfile.mjs
server/src/services/adminUsers/PartnerCreate.mjs
server/src/services/adminUsers/PartnerUpdate.mjs

- Handle partner domains order for ref page
- Show order number of domains items in admin partner profile settings
- Remove preselectedDomain from partner profile settings in db
- Handle alternative user on login in ref page with gated registrations

Fix. DASH-886 Multiple domain partner profile order

---

client/src/components/Badges/TokenBadge/TokenBadge.module.scss
client/src/components/Input/Input.module.scss
client/src/components/Input/TextInput.tsx
client/src/components/Modal/EmailModal/EmailModal.tsx
client/src/pages/WrapDomainPage/components/WarapDomainForm/WrapDomainForm.tsx
client/src/pages/WrapTokensPage/components/WrapTokensForm/WrapTokensForm.tsx

- Fix linked tokens item UI for mobile
- Fix resend recovery email modal background colour
- Fix input paddings for wrap tokens/domains in public address input field

Fix. DASH-549 Visual issues

---

client/src/pages/SettingsPage/components/DeleteMyAccount/DeleteMyAccount.tsx
server/src/services/users/Delete.mjs

- Remove user id from cart on user delete.
-  Do not show transaction processing on edge user delete.

DASH-971 Error on user delete if cart is not empty.

---

client/src/components/FioNameTransfer/FioNameTransferContainer.module.scss
client/src/components/FioNameTransfer/FioNameTransferContainer.tsx
client/src/components/InfoBadge/InfoBadge.tsx

- Fix text wrap of info badge in Transfer FIO Handle page
- Add text about social media links purge on transfer.

DASH-972 Fix UI in Transfer FIO Handle page.

---

client/src/api/responses.d.ts
client/src/components/GateVerificationComponent/GateVerificationComponent.module.scss
client/src/components/GateVerificationComponent/GateVerificationComponent.tsx
client/src/pages/AdminDefaultsPage/AdminDefaultsPage.tsx
client/src/pages/AdminDefaultsPage/components/AvailableDomains.tsx
client/src/pages/AdminDefaultsPage/components/DashboardDomains.tsx
client/src/pages/AdminDefaultsPage/components/SearchPostfixes.tsx
client/src/pages/AdminDefaultsPage/components/SearchPrefixes.tsx
client/src/pages/AdminDefaultsPage/components/UsernamesOnCustomDomains.tsx
client/src/pages/AdminPartnersListPage/AdminPartnersListPage.tsx
client/src/pages/AdminPartnersListPage/components/updatePartner/PartnerFormComponent.tsx
client/src/pages/RefHomePage/RefHomePage.tsx
client/src/pages/RefHomePage/RefHomePageContext.tsx
client/src/types.d.ts
server/src/jobs/domains-expiration.mjs
server/src/services/adminUsers/DefaultsSave.mjs
server/src/services/adminUsers/PartnerCreate.mjs
server/src/services/adminUsers/PartnerUpdate.mjs

- Handle domain expiration date on partner and default dashboard domains list save.
- Handle expired domain on gated registration.

DASH-883 Handle expired domain on gated registration. 

---

client/src/constants/cart.ts
client/src/constants/common.ts
client/src/pages/CartPage/CartPageContext.tsx
client/src/pages/CheckoutPage/CheckoutPageContext.tsx
server/src/services/cart/DeleteItem.mjs
server/src/services/cart/HandleUsersFreeCartItems.mjs

- Clear cart items if no cart in db on Delete cart item and handling free cart items on login-logout.

DASH-980 Fix something went wrong error on login and logout

---

client/src/pages/FioAddressSelectionPage/FioAddressSelectionPageContext.tsx

- Fix logic for suggested domains list.

Fix. DASH-997 Domain detect in fio handle select

---

client/src/api/admin.ts
client/src/pages/AdminRegularUserDetailsPage/AdminRegularUserDetailsPage.tsx
client/src/pages/AdminRegularUserDetailsPage/AdminRegularUserDetailsPageContext.tsx
client/src/pages/AdminRegularUserDetailsPage/components/UserInfo/UserInfo.tsx
client/src/pages/AdminRegularUsersListPage/AdminRegularUsersList.tsx
client/src/pages/AdminRegularUsersListPage/AdminRegularUsersListContext.tsx
client/src/pages/AdminRegularUsersListPage/constants.ts
client/src/redux/admin/actions.ts
client/src/types.d.ts
client/src/util/user.ts
server/src/config/constants.js
server/src/models/User.mjs
server/src/services/users/List.mjs
server/src/utils/user.mjs

Add user profile type in Admin pages:
- User details page
- Users list
- Export users list
- Users list filter

DASH-1007 Add user profile type in Admin pages.

---

server/src/utils/publicApi.mjs

Fix account_id type from string to number.

Develop > Staging [Hotfix Release 1.24]

---

client/src/pages/WalletPage/components/WalletSettings.tsx

Reverts fioprotocol/fio-dashboard#1791

Revert "DASH-1089 Fix delete wallet modal"

---

client/src/pages/CookieNoticePage/CookieNoticePage.tsx

- DASH-1143 Cookie yes visibility updates.

Develop > Staging

---

client/src/components/NoProfileFlowContainer/NoProfileFlowContainerContext.ts
client/src/pages/CookieNoticePage/CookieNoticePage.tsx
client/src/pages/NoProfileFlowRegisterFioHandlePage/NoProfileFlowRegisterFioHandleContext.ts
server/src/services/auth/AlternateAuthenticate.mjs
server/src/services/auth/Create.mjs
server/src/services/orders/Create.mjs
server/src/services/wallets/AddMissing.mjs

- Fix Add items on NO Profile flow. Fix error exception on server.

Staging > Main [Release 1.26][Hot fix]

---

server/src/services/cart/RecalculateOnPriceUpdate.mjs
server/src/services/orders/Create.mjs
server/src/utils/cart.mjs

- DASH-1224. Recalculate prices on order creation.

Develop > Staging [Release 1.27][Hotfix]

---

client/src/api/fio.ts
client/src/pages/FioAddressSelectionPage/FioAddressSelectionPageContext.tsx
client/src/pages/MainLayout/MainLayout.tsx
client/src/pages/MainLayout/index.ts
client/src/redux/registrations/reducer.ts
client/src/redux/sagas.ts
client/src/redux/settings/sagas.ts
server/src/services/general/GetSiteSettings.mjs

* Get raw abi from the backend along with api urls in settings endpoint. 
* Refactor setting abi values.

DASH-1259. Get/set raw abi changes.

---

server/src/models/Order.mjs
server/src/models/Payment.mjs
server/src/services/cart/CreateCartFromOrder.mjs
server/src/services/orders/Get.mjs
server/src/services/orders/ProcessPayment.mjs
server/src/services/orders/WsStatus.mjs
server/src/services/updateOrderStatus.mjs

* Refactor orderInfo, separate query
* Refactor usage of order info and getting order for user and admin.

DASH-1299. OrderInfo changes

---

server/src/external/fio.mjs
server/src/jobs/tx-check.mjs

* Check fch or domain registered by table rows call instead of fio names in tx-check job.

DASH-1324. Check fch or domain registered changes

---

server/src/jobs/tx-check.mjs

* Fix getTransaction result handling. 
* Set failed status to tx when exceeds max iterations.

DASH-1324. Get tx call res issues in tx-check job

---

server/src/jobs/orders.mjs
server/src/services/orders/Create.mjs
server/src/services/publicApi/BuyAddress.mjs
server/src/services/publicApi/Renew.mjs
server/src/utils/payment.mjs

Staging > Main [Hotfix]

---

server/src/services/auth/AlternateAuthenticate.mjs
server/src/services/auth/Create.mjs
server/src/tools.mjs

- Remove location from email trigger
- Don't wait for device check on login.

DASH-1292 Send email on device change fixes

---

server/src/migrations/20250324122717-add-missing-flag-to-wallets.js
server/src/models/Wallet.mjs
server/src/services/wallets/AddMissing.mjs

* Add missing wallet once, add missing flag to wallets, missing wallet is not available.

DASH-1374. Missing wallet changes.

---

client/src/constants/errors.ts
client/src/pages/SettingsPage/components/ChangeEmail/ChangeEmail.tsx
client/src/pages/SettingsPage/components/DeleteMyAccount/DeleteMyAccount.tsx
client/src/pages/WalletPage/components/WalletSettings.tsx
client/src/pages/WalletsPage/components/CreateWallet/CreateLedgerWallet.tsx
client/src/pages/WalletsPage/components/CreateWallet/CreateMetamaskWallet.tsx
client/src/services/api/wallet/metamask.ts

Do not show general error on metamask sign rejection

DASH-1339. Handle metamask reject on nonce verification actions

---

server/src/external/fio.mjs
server/src/jobs/orders.mjs
server/src/jobs/tx-check.mjs

- Add more logs for orders cron jobs.
- Handle checking expiration transaction for renew and add bundles on `tx-check` cron job.

DASH-1405 Add more logs for order cron jobs.

---

server/src/jobs/retry-forked-transactions.mjs

- Include Partial successed orders to retry orders too.

DASH-1407 Retry forked transaction cron job update

---

client/src/components/Cart/Cart.module.scss
client/src/components/Cart/CartItem.tsx
client/src/components/SelectionItem/components/DomainPeriodDropdown/DomainPeriodDropdown.module.scss
client/src/components/SelectionItem/components/DomainPeriodDropdown/DomainPeriodDropdown.tsx
client/src/constants/common.ts
client/src/pages/FioDomainManagePage/FioDomainManagePageContext.tsx
client/src/pages/FioDomainSelectionPage/FioDomainSelectionPageContext.tsx
server/src/config/constants.js

- Implement new domain renew years list

Staging > Main [Lifetime domain micro release 1.0]

---

client/src/components/Cart/Cart.tsx
client/src/hooks/refProfile.ts
client/src/pages/FioAddressCustomSelectionPage/components/SelectedItemComponent/SelectedItemComponentContext.tsx
client/src/pages/FioAddressSelectionPage/FioAddressSelectionPageContext.tsx
client/src/pages/FioAffiliateProgramPage/FioAffiliateProgramPageContext.tsx
client/src/pages/FioDomainLandingPage/FioDomainLandingPageContext.tsx
client/src/pages/FioDomainManagePage/FioDomainManagePageContext.tsx
client/src/pages/FioDomainRenewPage/FioDomainRenewPage.tsx
client/src/pages/FioDomainSelectionPage/FioDomainSelectionPageContext.tsx
client/src/pages/MetamaskGatedRegistration/MetamaskGatedRegistrationContext.tsx
client/src/pages/NoProfileFlowRegisterFioDomainPage/NoProfileFlowRegisterFioDomainPageContext.ts
client/src/pages/NoProfileFlowRegisterFioHandlePage/NoProfileFlowRegisterFioHandleContext.ts
client/src/pages/NoProfileFlowRenewFioDomainPage/NoProfileFlowRenewFioDomainPageContext.ts
client/src/pages/OrderDetailsPage/OrderDetailsPage.module.scss
client/src/pages/OrderDetailsPage/components/OrderItem/OrderItem.tsx
client/src/pages/RefHomePage/RefHomePageContext.tsx
client/src/pages/TwitterPage/TwitterPage.tsx
client/src/redux/cart/actions.ts
client/src/redux/cart/sagas.ts
client/src/util/cart.ts
client/src/util/prices.ts

- Cover all domains and renew domains registrations with 50 years default renew time.
- Add accordion for purchase page on big amount of transactoins.

Staging > Main [Lifetime domain micro release 1.1]

---

client/src/hooks/governance.ts
client/src/pages/GovernancePage/components/WalletVotesDetailsModal/components/ProxyVoteDetails/ProxyVoteDetails.tsx
client/src/pages/GovernancePage/components/WalletVotesDetailsModal/components/WalletBlockProducersTab/WalletBlockProducersTab.tsx
client/src/pages/GovernancePage/components/WalletVotesDetailsModal/components/WalletBoardOfDirectorsTab/WalletBoardOfDirectorsTab.module.scss
client/src/pages/GovernancePage/components/WalletVotesDetailsModal/components/WalletBoardOfDirectorsTab/WalletBoardOfDirectorsTab.tsx
client/src/routes.tsx
client/src/types/governance.d.ts

- Fix board members show for current wallet. 
- Move governance page into private route.
- Fix block producer's current voting power for wallet details.

DASH-1396 Governance Page fixes
